=head1 TITLE

System Configurator Test Cases

=head1 DESCRIPTION

This document is meant to provide a brief overview of how to
contribute test cases to the System Configurator project, and what
those test cases are expected to do.

=head1 BASIC STRUCTURE

Every module that is checked into the System Configurator tree should
have its own test case which stresses the code in such a way that you
can be fairly confident that it does what you think it should do.

An example of this code

