# This Makefile is for the systemconfigurator extension to perl.
#
# It was generated automatically by MakeMaker version
# 6.57_05 (Revision: 65705) from the contents of
# Makefile.PL. Don't edit this file, edit Makefile.PL instead.
#
#       ANY CHANGES MADE HERE WILL BE LOST!
#
#   MakeMaker ARGV: ()
#

#   MakeMaker Parameters:

#     BUILD_REQUIRES => {  }
#     EXE_FILES => [q[bin/systemconfigurator], q[bin/scconf-tool], q[bin/scconf-bootinfo]]
#     INSTALLSITELIB => q[/usr/lib/systemconfig]
#     MAN1PODS => { bin/systemconfigurator=>q[$(INST_MAN1DIR)/systemconfigurator.$(MAN1EXT)] }
#     MAN3PODS => {  }
#     NAME => q[systemconfigurator]
#     PREREQ_PM => { AppConfig=>q[1.52] }
#     VERSION => q[2.2.11]
#     macro => { MAN3EXT=>q[3pm], MAN1EXT=>q[1] }
#     realclean => { FILES=>q[*.old *.bak *.tar.gz *.yml *.spec Makefile MANIFEST] }

# --- MakeMaker post_initialize section:


# --- MakeMaker const_config section:

# These definitions are from config.sh (via /usr/lib/perl/5.14/Config.pm).
# They may have been overridden via Makefile.PL or on the command line.
AR = ar
CC = cc
CCCDLFLAGS = -fPIC
CCDLFLAGS = -Wl,-E
DLEXT = so
DLSRC = dl_dlopen.xs
EXE_EXT = 
FULL_AR = /usr/bin/ar
LD = cc
LDDLFLAGS = -shared -L/usr/local/lib -fstack-protector
LDFLAGS =  -fstack-protector -L/usr/local/lib
LIBC = 
LIB_EXT = .a
OBJ_EXT = .o
OSNAME = linux
OSVERS = 3.2.0-4-amd64
RANLIB = :
SITELIBEXP = /usr/local/share/perl/5.14.2
SITEARCHEXP = /usr/local/lib/perl/5.14.2
SO = so
VENDORARCHEXP = /usr/lib/perl5
VENDORLIBEXP = /usr/share/perl5


# --- MakeMaker constants section:
AR_STATIC_ARGS = cr
DIRFILESEP = /
DFSEP = $(DIRFILESEP)
NAME = systemconfigurator
NAME_SYM = systemconfigurator
VERSION = 2.2.11
VERSION_MACRO = VERSION
VERSION_SYM = 2_2_11
DEFINE_VERSION = -D$(VERSION_MACRO)=\"$(VERSION)\"
XS_VERSION = 2.2.11
XS_VERSION_MACRO = XS_VERSION
XS_DEFINE_VERSION = -D$(XS_VERSION_MACRO)=\"$(XS_VERSION)\"
INST_ARCHLIB = blib/arch
INST_SCRIPT = blib/script
INST_BIN = blib/bin
INST_LIB = blib/lib
INST_MAN1DIR = blib/man1
INST_MAN3DIR = blib/man3
MAN1EXT = 1p
MAN3EXT = 3pm
INSTALLDIRS = site
DESTDIR = 
PREFIX = /usr
PERLPREFIX = $(PREFIX)
SITEPREFIX = $(PREFIX)/local
VENDORPREFIX = $(PREFIX)
INSTALLPRIVLIB = $(PERLPREFIX)/share/perl/5.14
DESTINSTALLPRIVLIB = $(DESTDIR)$(INSTALLPRIVLIB)
INSTALLSITELIB = /usr/lib/systemconfig
DESTINSTALLSITELIB = $(DESTDIR)$(INSTALLSITELIB)
INSTALLVENDORLIB = $(VENDORPREFIX)/share/perl5
DESTINSTALLVENDORLIB = $(DESTDIR)$(INSTALLVENDORLIB)
INSTALLARCHLIB = $(PERLPREFIX)/lib/perl/5.14
DESTINSTALLARCHLIB = $(DESTDIR)$(INSTALLARCHLIB)
INSTALLSITEARCH = /usr/lib/systemconfig
DESTINSTALLSITEARCH = $(DESTDIR)$(INSTALLSITEARCH)
INSTALLVENDORARCH = $(VENDORPREFIX)/lib/perl5
DESTINSTALLVENDORARCH = $(DESTDIR)$(INSTALLVENDORARCH)
INSTALLBIN = $(PERLPREFIX)/bin
DESTINSTALLBIN = $(DESTDIR)$(INSTALLBIN)
INSTALLSITEBIN = $(SITEPREFIX)/bin
DESTINSTALLSITEBIN = $(DESTDIR)$(INSTALLSITEBIN)
INSTALLVENDORBIN = $(VENDORPREFIX)/bin
DESTINSTALLVENDORBIN = $(DESTDIR)$(INSTALLVENDORBIN)
INSTALLSCRIPT = $(PERLPREFIX)/bin
DESTINSTALLSCRIPT = $(DESTDIR)$(INSTALLSCRIPT)
INSTALLSITESCRIPT = $(SITEPREFIX)/bin
DESTINSTALLSITESCRIPT = $(DESTDIR)$(INSTALLSITESCRIPT)
INSTALLVENDORSCRIPT = $(VENDORPREFIX)/bin
DESTINSTALLVENDORSCRIPT = $(DESTDIR)$(INSTALLVENDORSCRIPT)
INSTALLMAN1DIR = $(PERLPREFIX)/share/man/man1
DESTINSTALLMAN1DIR = $(DESTDIR)$(INSTALLMAN1DIR)
INSTALLSITEMAN1DIR = $(SITEPREFIX)/man/man1
DESTINSTALLSITEMAN1DIR = $(DESTDIR)$(INSTALLSITEMAN1DIR)
INSTALLVENDORMAN1DIR = $(VENDORPREFIX)/share/man/man1
DESTINSTALLVENDORMAN1DIR = $(DESTDIR)$(INSTALLVENDORMAN1DIR)
INSTALLMAN3DIR = $(PERLPREFIX)/share/man/man3
DESTINSTALLMAN3DIR = $(DESTDIR)$(INSTALLMAN3DIR)
INSTALLSITEMAN3DIR = $(SITEPREFIX)/man/man3
DESTINSTALLSITEMAN3DIR = $(DESTDIR)$(INSTALLSITEMAN3DIR)
INSTALLVENDORMAN3DIR = $(VENDORPREFIX)/share/man/man3
DESTINSTALLVENDORMAN3DIR = $(DESTDIR)$(INSTALLVENDORMAN3DIR)
PERL_LIB = /usr/share/perl/5.14
PERL_ARCHLIB = /usr/lib/perl/5.14
LIBPERL_A = libperl.a
FIRST_MAKEFILE = Makefile
MAKEFILE_OLD = Makefile.old
MAKE_APERL_FILE = Makefile.aperl
PERLMAINCC = $(CC)
PERL_INC = /usr/lib/perl/5.14/CORE
PERL = /usr/bin/perl
FULLPERL = /usr/bin/perl
ABSPERL = $(PERL)
PERLRUN = $(PERL)
FULLPERLRUN = $(FULLPERL)
ABSPERLRUN = $(ABSPERL)
PERLRUNINST = $(PERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"
FULLPERLRUNINST = $(FULLPERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"
ABSPERLRUNINST = $(ABSPERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"
PERL_CORE = 0
PERM_DIR = 755
PERM_RW = 644
PERM_RWX = 755

MAKEMAKER   = /usr/share/perl/5.14/ExtUtils/MakeMaker.pm
MM_VERSION  = 6.57_05
MM_REVISION = 65705

# FULLEXT = Pathname for extension directory (eg Foo/Bar/Oracle).
# BASEEXT = Basename part of FULLEXT. May be just equal FULLEXT. (eg Oracle)
# PARENT_NAME = NAME without BASEEXT and no trailing :: (eg Foo::Bar)
# DLBASE  = Basename part of dynamic library. May be just equal BASEEXT.
MAKE = make
FULLEXT = systemconfigurator
BASEEXT = systemconfigurator
PARENT_NAME = 
DLBASE = $(BASEEXT)
VERSION_FROM = 
OBJECT = 
LDFROM = $(OBJECT)
LINKTYPE = dynamic
BOOTDEP = 

# Handy lists of source code files:
XS_FILES = 
C_FILES  = 
O_FILES  = 
H_FILES  = 
MAN1PODS = bin/systemconfigurator
MAN3PODS = 

# Where is the Config information that we are using/depend on
CONFIGDEP = $(PERL_ARCHLIB)$(DFSEP)Config.pm $(PERL_INC)$(DFSEP)config.h

# Where to build things
INST_LIBDIR      = $(INST_LIB)
INST_ARCHLIBDIR  = $(INST_ARCHLIB)

INST_AUTODIR     = $(INST_LIB)/auto/$(FULLEXT)
INST_ARCHAUTODIR = $(INST_ARCHLIB)/auto/$(FULLEXT)

INST_STATIC      = 
INST_DYNAMIC     = 
INST_BOOT        = 

# Extra linker info
EXPORT_LIST        = 
PERL_ARCHIVE       = 
PERL_ARCHIVE_AFTER = 


TO_INST_PM = lib/Boot.pm \
	lib/Boot/Aboot.pm \
	lib/Boot/Devfs.pm \
	lib/Boot/EFI.pm \
	lib/Boot/Elilo.pm \
	lib/Boot/Grub.pm \
	lib/Boot/Iseries.pm \
	lib/Boot/Kboot.pm \
	lib/Boot/Label.pm \
	lib/Boot/Lilo.pm \
	lib/Boot/Palo.pm \
	lib/Boot/Path.pm \
	lib/Boot/YaBoot.pm \
	lib/Boot/ZIPL.pm \
	lib/Hardware.pm \
	lib/Hardware/PCI/Detect.pm \
	lib/Hardware/PCI/Table.pm \
	lib/Hardware/iSeries.pm \
	lib/Initrd.pm \
	lib/Initrd/Debian.pm \
	lib/Initrd/Generic.pm \
	lib/Initrd/RH.pm \
	lib/Initrd/SuSE.pm \
	lib/Initrd2.pm \
	lib/Keyboard.pm \
	lib/Modules/ConfModules.pm \
	lib/Modules/Deps.pm \
	lib/Modules/Generic.pm \
	lib/Modules/ModprobeConf.pm \
	lib/Modules/ModprobeD.pm \
	lib/Modules/ModulesConf.pm \
	lib/Modules/ModutilsAliases.pm \
	lib/Modules/RcConfig.pm \
	lib/Modules/Root.pm \
	lib/Modules/SuSE8.pm \
	lib/Net/Netmask.pm \
	lib/Network.pm \
	lib/Network/Generic.pm \
	lib/Network/Interface.pm \
	lib/Network/Interfaces.pm \
	lib/Network/LinuxConf.pm \
	lib/Network/RCConfig.pm \
	lib/Network/RawNetwork.pm \
	lib/Network/SuSE8.pm \
	lib/SCConfig.pm \
	lib/Time.pm \
	lib/Time/HWSync.pm \
	lib/Time/NTP.pm \
	lib/Time/Rdate.pm \
	lib/Time/Zone.pm \
	lib/Time/Zone/Debian.pm \
	lib/Time/Zone/Generic.pm \
	lib/Time/Zone/RH.pm \
	lib/Time/Zone/SuSE8.pm \
	lib/UserExit.pm \
	lib/Util/Cmd.pm \
	lib/Util/FileMod.pm \
	lib/Util/Log.pm

PM_TO_BLIB = lib/Network/RCConfig.pm \
	blib/lib/Network/RCConfig.pm \
	lib/Boot/Label.pm \
	blib/lib/Boot/Label.pm \
	lib/Boot/Lilo.pm \
	blib/lib/Boot/Lilo.pm \
	lib/Boot/EFI.pm \
	blib/lib/Boot/EFI.pm \
	lib/Modules/Root.pm \
	blib/lib/Modules/Root.pm \
	lib/Modules/Generic.pm \
	blib/lib/Modules/Generic.pm \
	lib/Network/RawNetwork.pm \
	blib/lib/Network/RawNetwork.pm \
	lib/Network/SuSE8.pm \
	blib/lib/Network/SuSE8.pm \
	lib/SCConfig.pm \
	blib/lib/SCConfig.pm \
	lib/Modules/ModprobeConf.pm \
	blib/lib/Modules/ModprobeConf.pm \
	lib/Initrd/Generic.pm \
	blib/lib/Initrd/Generic.pm \
	lib/Boot/Grub.pm \
	blib/lib/Boot/Grub.pm \
	lib/Boot/Palo.pm \
	blib/lib/Boot/Palo.pm \
	lib/Util/Cmd.pm \
	blib/lib/Util/Cmd.pm \
	lib/Boot/Devfs.pm \
	blib/lib/Boot/Devfs.pm \
	lib/Time/Zone/RH.pm \
	blib/lib/Time/Zone/RH.pm \
	lib/Boot/Path.pm \
	blib/lib/Boot/Path.pm \
	lib/Hardware.pm \
	blib/lib/Hardware.pm \
	lib/Time/Zone/Generic.pm \
	blib/lib/Time/Zone/Generic.pm \
	lib/Modules/RcConfig.pm \
	blib/lib/Modules/RcConfig.pm \
	lib/Hardware/PCI/Table.pm \
	blib/lib/Hardware/PCI/Table.pm \
	lib/UserExit.pm \
	blib/lib/UserExit.pm \
	lib/Boot.pm \
	blib/lib/Boot.pm \
	lib/Initrd2.pm \
	blib/lib/Initrd2.pm \
	lib/Network/Interface.pm \
	blib/lib/Network/Interface.pm \
	lib/Modules/ModulesConf.pm \
	blib/lib/Modules/ModulesConf.pm \
	lib/Hardware/iSeries.pm \
	blib/lib/Hardware/iSeries.pm \
	lib/Boot/Iseries.pm \
	blib/lib/Boot/Iseries.pm \
	lib/Network/LinuxConf.pm \
	blib/lib/Network/LinuxConf.pm \
	lib/Initrd/Debian.pm \
	blib/lib/Initrd/Debian.pm \
	lib/Network/Generic.pm \
	blib/lib/Network/Generic.pm \
	lib/Time/HWSync.pm \
	blib/lib/Time/HWSync.pm \
	lib/Initrd/SuSE.pm \
	blib/lib/Initrd/SuSE.pm \
	lib/Modules/SuSE8.pm \
	blib/lib/Modules/SuSE8.pm \
	lib/Time/Zone/SuSE8.pm \
	blib/lib/Time/Zone/SuSE8.pm \
	lib/Util/FileMod.pm \
	blib/lib/Util/FileMod.pm \
	lib/Time/Rdate.pm \
	blib/lib/Time/Rdate.pm \
	lib/Initrd.pm \
	blib/lib/Initrd.pm \
	lib/Initrd/RH.pm \
	blib/lib/Initrd/RH.pm \
	lib/Boot/Aboot.pm \
	blib/lib/Boot/Aboot.pm \
	lib/Hardware/PCI/Detect.pm \
	blib/lib/Hardware/PCI/Detect.pm \
	lib/Time/Zone/Debian.pm \
	blib/lib/Time/Zone/Debian.pm \
	lib/Time.pm \
	blib/lib/Time.pm \
	lib/Keyboard.pm \
	blib/lib/Keyboard.pm \
	lib/Network.pm \
	blib/lib/Network.pm \
	lib/Modules/ConfModules.pm \
	blib/lib/Modules/ConfModules.pm \
	lib/Boot/Kboot.pm \
	blib/lib/Boot/Kboot.pm \
	lib/Time/NTP.pm \
	blib/lib/Time/NTP.pm \
	lib/Time/Zone.pm \
	blib/lib/Time/Zone.pm \
	lib/Boot/ZIPL.pm \
	blib/lib/Boot/ZIPL.pm \
	lib/Modules/ModutilsAliases.pm \
	blib/lib/Modules/ModutilsAliases.pm \
	lib/Boot/YaBoot.pm \
	blib/lib/Boot/YaBoot.pm \
	lib/Net/Netmask.pm \
	blib/lib/Net/Netmask.pm \
	lib/Network/Interfaces.pm \
	blib/lib/Network/Interfaces.pm \
	lib/Modules/Deps.pm \
	blib/lib/Modules/Deps.pm \
	lib/Util/Log.pm \
	blib/lib/Util/Log.pm \
	lib/Boot/Elilo.pm \
	blib/lib/Boot/Elilo.pm \
	lib/Modules/ModprobeD.pm \
	blib/lib/Modules/ModprobeD.pm


# --- MakeMaker platform_constants section:
MM_Unix_VERSION = 6.57_05
PERL_MALLOC_DEF = -DPERL_EXTMALLOC_DEF -Dmalloc=Perl_malloc -Dfree=Perl_mfree -Drealloc=Perl_realloc -Dcalloc=Perl_calloc


# --- MakeMaker tool_autosplit section:
# Usage: $(AUTOSPLITFILE) FileToSplit AutoDirToSplitInto
AUTOSPLITFILE = $(ABSPERLRUN)  -e 'use AutoSplit;  autosplit($$ARGV[0], $$ARGV[1], 0, 1, 1)' --



# --- MakeMaker tool_xsubpp section:


# --- MakeMaker tools_other section:
SHELL = /bin/sh
CHMOD = chmod
CP = cp
MV = mv
NOOP = $(TRUE)
NOECHO = @
RM_F = rm -f
RM_RF = rm -rf
TEST_F = test -f
TOUCH = touch
UMASK_NULL = umask 0
DEV_NULL = > /dev/null 2>&1
MKPATH = $(ABSPERLRUN) -MExtUtils::Command -e 'mkpath' --
EQUALIZE_TIMESTAMP = $(ABSPERLRUN) -MExtUtils::Command -e 'eqtime' --
FALSE = false
TRUE = true
ECHO = echo
ECHO_N = echo -n
UNINST = 0
VERBINST = 0
MOD_INSTALL = $(ABSPERLRUN) -MExtUtils::Install -e 'install([ from_to => {@ARGV}, verbose => '\''$(VERBINST)'\'', uninstall_shadows => '\''$(UNINST)'\'', dir_mode => '\''$(PERM_DIR)'\'' ]);' --
DOC_INSTALL = $(ABSPERLRUN) -MExtUtils::Command::MM -e 'perllocal_install' --
UNINSTALL = $(ABSPERLRUN) -MExtUtils::Command::MM -e 'uninstall' --
WARN_IF_OLD_PACKLIST = $(ABSPERLRUN) -MExtUtils::Command::MM -e 'warn_if_old_packlist' --
MACROSTART = 
MACROEND = 
USEMAKEFILE = -f
FIXIN = $(ABSPERLRUN) -MExtUtils::MY -e 'MY->fixin(shift)' --


# --- MakeMaker makemakerdflt section:
makemakerdflt : all
	$(NOECHO) $(NOOP)


# --- MakeMaker dist section:
TAR = tar
TARFLAGS = cvf
ZIP = zip
ZIPFLAGS = -r
COMPRESS = gzip --best
SUFFIX = .gz
SHAR = shar
PREOP = $(NOECHO) $(NOOP)
POSTOP = $(NOECHO) $(NOOP)
TO_UNIX = $(NOECHO) $(NOOP)
CI = ci -u
RCS_LABEL = rcs -Nv$(VERSION_SYM): -q
DIST_CP = best
DIST_DEFAULT = tardist
DISTNAME = systemconfigurator
DISTVNAME = systemconfigurator-2.2.11


# --- MakeMaker macro section:
MAN3EXT = 3pm
MAN1EXT = 1


# --- MakeMaker depend section:


# --- MakeMaker cflags section:


# --- MakeMaker const_loadlibs section:


# --- MakeMaker const_cccmd section:


# --- MakeMaker post_constants section:


# --- MakeMaker pasthru section:

PASTHRU = LIBPERL_A="$(LIBPERL_A)"\
	LINKTYPE="$(LINKTYPE)"\
	LD="$(LD)"\
	PREFIX="$(PREFIX)"


# --- MakeMaker special_targets section:
.SUFFIXES : .xs .c .C .cpp .i .s .cxx .cc $(OBJ_EXT)

.PHONY: all config static dynamic test linkext manifest blibdirs clean realclean disttest distdir



# --- MakeMaker c_o section:


# --- MakeMaker xs_c section:


# --- MakeMaker xs_o section:


# --- MakeMaker top_targets section:
all :: pure_all manifypods
	$(NOECHO) $(NOOP)


pure_all :: config pm_to_blib subdirs linkext
	$(NOECHO) $(NOOP)

subdirs :: $(MYEXTLIB)
	$(NOECHO) $(NOOP)

config :: $(FIRST_MAKEFILE) blibdirs
	$(NOECHO) $(NOOP)

help :
	perldoc ExtUtils::MakeMaker


# --- MakeMaker blibdirs section:
blibdirs : $(INST_LIBDIR)$(DFSEP).exists $(INST_ARCHLIB)$(DFSEP).exists $(INST_AUTODIR)$(DFSEP).exists $(INST_ARCHAUTODIR)$(DFSEP).exists $(INST_BIN)$(DFSEP).exists $(INST_SCRIPT)$(DFSEP).exists $(INST_MAN1DIR)$(DFSEP).exists $(INST_MAN3DIR)$(DFSEP).exists
	$(NOECHO) $(NOOP)

# Backwards compat with 6.18 through 6.25
blibdirs.ts : blibdirs
	$(NOECHO) $(NOOP)

$(INST_LIBDIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_LIBDIR)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_LIBDIR)
	$(NOECHO) $(TOUCH) $(INST_LIBDIR)$(DFSEP).exists

$(INST_ARCHLIB)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_ARCHLIB)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_ARCHLIB)
	$(NOECHO) $(TOUCH) $(INST_ARCHLIB)$(DFSEP).exists

$(INST_AUTODIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_AUTODIR)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_AUTODIR)
	$(NOECHO) $(TOUCH) $(INST_AUTODIR)$(DFSEP).exists

$(INST_ARCHAUTODIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_ARCHAUTODIR)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_ARCHAUTODIR)
	$(NOECHO) $(TOUCH) $(INST_ARCHAUTODIR)$(DFSEP).exists

$(INST_BIN)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_BIN)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_BIN)
	$(NOECHO) $(TOUCH) $(INST_BIN)$(DFSEP).exists

$(INST_SCRIPT)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_SCRIPT)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_SCRIPT)
	$(NOECHO) $(TOUCH) $(INST_SCRIPT)$(DFSEP).exists

$(INST_MAN1DIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_MAN1DIR)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_MAN1DIR)
	$(NOECHO) $(TOUCH) $(INST_MAN1DIR)$(DFSEP).exists

$(INST_MAN3DIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_MAN3DIR)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_MAN3DIR)
	$(NOECHO) $(TOUCH) $(INST_MAN3DIR)$(DFSEP).exists



# --- MakeMaker linkext section:

linkext :: $(LINKTYPE)
	$(NOECHO) $(NOOP)


# --- MakeMaker dlsyms section:


# --- MakeMaker dynamic section:

dynamic :: $(FIRST_MAKEFILE) $(INST_DYNAMIC) $(INST_BOOT)
	$(NOECHO) $(NOOP)


# --- MakeMaker dynamic_bs section:

BOOTSTRAP =


# --- MakeMaker dynamic_lib section:


# --- MakeMaker static section:

## $(INST_PM) has been moved to the all: target.
## It remains here for awhile to allow for old usage: "make static"
static :: $(FIRST_MAKEFILE) $(INST_STATIC)
	$(NOECHO) $(NOOP)


# --- MakeMaker static_lib section:


# --- MakeMaker manifypods section:

POD2MAN_EXE = $(PERLRUN) "-MExtUtils::Command::MM" -e pod2man "--"
POD2MAN = $(POD2MAN_EXE)


manifypods : pure_all  \
	bin/systemconfigurator
	$(NOECHO) $(POD2MAN) --section=$(MAN1EXT) --perm_rw=$(PERM_RW) \
	  bin/systemconfigurator $(INST_MAN1DIR)/systemconfigurator.$(MAN1EXT) 




# --- MakeMaker processPL section:


# --- MakeMaker installbin section:

EXE_FILES = bin/systemconfigurator bin/scconf-tool bin/scconf-bootinfo

pure_all :: $(INST_SCRIPT)/scconf-tool $(INST_SCRIPT)/scconf-bootinfo $(INST_SCRIPT)/systemconfigurator
	$(NOECHO) $(NOOP)

realclean ::
	$(RM_F) \
	  $(INST_SCRIPT)/scconf-tool $(INST_SCRIPT)/scconf-bootinfo \
	  $(INST_SCRIPT)/systemconfigurator 

$(INST_SCRIPT)/scconf-tool : bin/scconf-tool $(FIRST_MAKEFILE) $(INST_SCRIPT)$(DFSEP).exists $(INST_BIN)$(DFSEP).exists
	$(NOECHO) $(RM_F) $(INST_SCRIPT)/scconf-tool
	$(CP) bin/scconf-tool $(INST_SCRIPT)/scconf-tool
	$(FIXIN) $(INST_SCRIPT)/scconf-tool
	-$(NOECHO) $(CHMOD) $(PERM_RWX) $(INST_SCRIPT)/scconf-tool

$(INST_SCRIPT)/scconf-bootinfo : bin/scconf-bootinfo $(FIRST_MAKEFILE) $(INST_SCRIPT)$(DFSEP).exists $(INST_BIN)$(DFSEP).exists
	$(NOECHO) $(RM_F) $(INST_SCRIPT)/scconf-bootinfo
	$(CP) bin/scconf-bootinfo $(INST_SCRIPT)/scconf-bootinfo
	$(FIXIN) $(INST_SCRIPT)/scconf-bootinfo
	-$(NOECHO) $(CHMOD) $(PERM_RWX) $(INST_SCRIPT)/scconf-bootinfo

$(INST_SCRIPT)/systemconfigurator : bin/systemconfigurator $(FIRST_MAKEFILE) $(INST_SCRIPT)$(DFSEP).exists $(INST_BIN)$(DFSEP).exists
	$(NOECHO) $(RM_F) $(INST_SCRIPT)/systemconfigurator
	$(CP) bin/systemconfigurator $(INST_SCRIPT)/systemconfigurator
	$(FIXIN) $(INST_SCRIPT)/systemconfigurator
	-$(NOECHO) $(CHMOD) $(PERM_RWX) $(INST_SCRIPT)/systemconfigurator



# --- MakeMaker subdirs section:

# none

# --- MakeMaker clean_subdirs section:
clean_subdirs :
	$(NOECHO) $(NOOP)


# --- MakeMaker clean section:

# Delete temporary files but do not touch installed files. We don't delete
# the Makefile here so a later make realclean still has a makefile to use.

clean :: clean_subdirs
	- $(RM_F) \
	  *$(LIB_EXT) core \
	  core.[0-9] $(INST_ARCHAUTODIR)/extralibs.all \
	  core.[0-9][0-9] $(BASEEXT).bso \
	  pm_to_blib.ts core.[0-9][0-9][0-9][0-9] \
	  MYMETA.yml $(BASEEXT).x \
	  $(BOOTSTRAP) perl$(EXE_EXT) \
	  tmon.out *$(OBJ_EXT) \
	  pm_to_blib $(INST_ARCHAUTODIR)/extralibs.ld \
	  blibdirs.ts core.[0-9][0-9][0-9][0-9][0-9] \
	  *perl.core core.*perl.*.? \
	  $(MAKE_APERL_FILE) $(BASEEXT).def \
	  perl core.[0-9][0-9][0-9] \
	  mon.out lib$(BASEEXT).def \
	  perlmain.c perl.exe \
	  so_locations $(BASEEXT).exp 
	- $(RM_RF) \
	  blib 
	- $(MV) $(FIRST_MAKEFILE) $(MAKEFILE_OLD) $(DEV_NULL)


# --- MakeMaker realclean_subdirs section:
realclean_subdirs :
	$(NOECHO) $(NOOP)


# --- MakeMaker realclean section:
# Delete temporary files (via clean) and also delete dist files
realclean purge ::  clean realclean_subdirs
	- $(RM_F) \
	  $(MAKEFILE_OLD) $(FIRST_MAKEFILE) 
	- $(RM_RF) \
	  *.spec *.old \
	  *.bak *.yml \
	  *.tar.gz MANIFEST \
	  $(DISTVNAME) Makefile 


# --- MakeMaker metafile section:
metafile : create_distdir
	$(NOECHO) $(ECHO) Generating META.yml
	$(NOECHO) $(ECHO) '--- #YAML:1.0' > META_new.yml
	$(NOECHO) $(ECHO) 'name:               systemconfigurator' >> META_new.yml
	$(NOECHO) $(ECHO) 'version:            2.2.11' >> META_new.yml
	$(NOECHO) $(ECHO) 'abstract:           ~' >> META_new.yml
	$(NOECHO) $(ECHO) 'author:  []' >> META_new.yml
	$(NOECHO) $(ECHO) 'license:            unknown' >> META_new.yml
	$(NOECHO) $(ECHO) 'distribution_type:  module' >> META_new.yml
	$(NOECHO) $(ECHO) 'configure_requires:' >> META_new.yml
	$(NOECHO) $(ECHO) '    ExtUtils::MakeMaker:  0' >> META_new.yml
	$(NOECHO) $(ECHO) 'build_requires:' >> META_new.yml
	$(NOECHO) $(ECHO) '    ExtUtils::MakeMaker:  0' >> META_new.yml
	$(NOECHO) $(ECHO) 'requires:' >> META_new.yml
	$(NOECHO) $(ECHO) '    AppConfig:  1.52' >> META_new.yml
	$(NOECHO) $(ECHO) 'no_index:' >> META_new.yml
	$(NOECHO) $(ECHO) '    directory:' >> META_new.yml
	$(NOECHO) $(ECHO) '        - t' >> META_new.yml
	$(NOECHO) $(ECHO) '        - inc' >> META_new.yml
	$(NOECHO) $(ECHO) 'generated_by:       ExtUtils::MakeMaker version 6.57_05' >> META_new.yml
	$(NOECHO) $(ECHO) 'meta-spec:' >> META_new.yml
	$(NOECHO) $(ECHO) '    url:      http://module-build.sourceforge.net/META-spec-v1.4.html' >> META_new.yml
	$(NOECHO) $(ECHO) '    version:  1.4' >> META_new.yml
	-$(NOECHO) $(MV) META_new.yml $(DISTVNAME)/META.yml


# --- MakeMaker signature section:
signature :
	cpansign -s


# --- MakeMaker dist_basics section:
distclean :: realclean distcheck
	$(NOECHO) $(NOOP)

distcheck :
	$(PERLRUN) "-MExtUtils::Manifest=fullcheck" -e fullcheck

skipcheck :
	$(PERLRUN) "-MExtUtils::Manifest=skipcheck" -e skipcheck

manifest :
	$(PERLRUN) "-MExtUtils::Manifest=mkmanifest" -e mkmanifest

veryclean : realclean
	$(RM_F) *~ */*~ *.orig */*.orig *.bak */*.bak *.old */*.old 



# --- MakeMaker dist_core section:

dist : $(DIST_DEFAULT) $(FIRST_MAKEFILE)
	$(NOECHO) $(ABSPERLRUN) -l -e 'print '\''Warning: Makefile possibly out of date with $(VERSION_FROM)'\''' \
	  -e '    if -e '\''$(VERSION_FROM)'\'' and -M '\''$(VERSION_FROM)'\'' < -M '\''$(FIRST_MAKEFILE)'\'';' --

tardist : $(DISTVNAME).tar$(SUFFIX)
	$(NOECHO) $(NOOP)

uutardist : $(DISTVNAME).tar$(SUFFIX)
	uuencode $(DISTVNAME).tar$(SUFFIX) $(DISTVNAME).tar$(SUFFIX) > $(DISTVNAME).tar$(SUFFIX)_uu

$(DISTVNAME).tar$(SUFFIX) : distdir
	$(PREOP)
	$(TO_UNIX)
	$(TAR) $(TARFLAGS) $(DISTVNAME).tar $(DISTVNAME)
	$(RM_RF) $(DISTVNAME)
	$(COMPRESS) $(DISTVNAME).tar
	$(POSTOP)

zipdist : $(DISTVNAME).zip
	$(NOECHO) $(NOOP)

$(DISTVNAME).zip : distdir
	$(PREOP)
	$(ZIP) $(ZIPFLAGS) $(DISTVNAME).zip $(DISTVNAME)
	$(RM_RF) $(DISTVNAME)
	$(POSTOP)

shdist : distdir
	$(PREOP)
	$(SHAR) $(DISTVNAME) > $(DISTVNAME).shar
	$(RM_RF) $(DISTVNAME)
	$(POSTOP)


# --- MakeMaker distdir section:
create_distdir :
	$(RM_RF) $(DISTVNAME)
	$(PERLRUN) "-MExtUtils::Manifest=manicopy,maniread" \
		-e "manicopy(maniread(),'$(DISTVNAME)', '$(DIST_CP)');"

distdir : create_distdir distmeta 
	$(NOECHO) $(NOOP)



# --- MakeMaker dist_test section:
disttest : distdir
	cd $(DISTVNAME) && $(ABSPERLRUN) Makefile.PL 
	cd $(DISTVNAME) && $(MAKE) $(PASTHRU)
	cd $(DISTVNAME) && $(MAKE) test $(PASTHRU)



# --- MakeMaker dist_ci section:

ci :
	$(PERLRUN) "-MExtUtils::Manifest=maniread" \
	  -e "@all = keys %{ maniread() };" \
	  -e "print(qq{Executing $(CI) @all\n}); system(qq{$(CI) @all});" \
	  -e "print(qq{Executing $(RCS_LABEL) ...\n}); system(qq{$(RCS_LABEL) @all});"


# --- MakeMaker distmeta section:
distmeta : create_distdir metafile
	$(NOECHO) cd $(DISTVNAME) && $(ABSPERLRUN) -MExtUtils::Manifest=maniadd -e 'eval { maniadd({q{META.yml} => q{Module meta-data (added by MakeMaker)}}) } ' \
	  -e '    or print "Could not add META.yml to MANIFEST: $${'\''@'\''}\n"' --



# --- MakeMaker distsignature section:
distsignature : create_distdir
	$(NOECHO) cd $(DISTVNAME) && $(ABSPERLRUN) -MExtUtils::Manifest=maniadd -e 'eval { maniadd({q{SIGNATURE} => q{Public-key signature (added by MakeMaker)}}) } ' \
	  -e '    or print "Could not add SIGNATURE to MANIFEST: $${'\''@'\''}\n"' --
	$(NOECHO) cd $(DISTVNAME) && $(TOUCH) SIGNATURE
	cd $(DISTVNAME) && cpansign -s



# --- MakeMaker install section:

install :: pure_install doc_install
	$(NOECHO) $(NOOP)

install_perl :: pure_perl_install doc_perl_install
	$(NOECHO) $(NOOP)

install_site :: pure_site_install doc_site_install
	$(NOECHO) $(NOOP)

install_vendor :: pure_vendor_install doc_vendor_install
	$(NOECHO) $(NOOP)

pure_install :: pure_$(INSTALLDIRS)_install
	$(NOECHO) $(NOOP)

doc_install :: doc_$(INSTALLDIRS)_install
	$(NOECHO) $(NOOP)

pure__install : pure_site_install
	$(NOECHO) $(ECHO) INSTALLDIRS not defined, defaulting to INSTALLDIRS=site

doc__install : doc_site_install
	$(NOECHO) $(ECHO) INSTALLDIRS not defined, defaulting to INSTALLDIRS=site

pure_perl_install :: all
	$(NOECHO) umask 022; $(MOD_INSTALL) \
		$(INST_LIB) $(DESTINSTALLPRIVLIB) \
		$(INST_ARCHLIB) $(DESTINSTALLARCHLIB) \
		$(INST_BIN) $(DESTINSTALLBIN) \
		$(INST_SCRIPT) $(DESTINSTALLSCRIPT) \
		$(INST_MAN1DIR) $(DESTINSTALLMAN1DIR) \
		$(INST_MAN3DIR) $(DESTINSTALLMAN3DIR)
	$(NOECHO) $(WARN_IF_OLD_PACKLIST) \
		$(SITEARCHEXP)/auto/$(FULLEXT)


pure_site_install :: all
	$(NOECHO) umask 02; $(MOD_INSTALL) \
		read $(SITEARCHEXP)/auto/$(FULLEXT)/.packlist \
		write $(DESTINSTALLSITEARCH)/auto/$(FULLEXT)/.packlist \
		$(INST_LIB) $(DESTINSTALLSITELIB) \
		$(INST_ARCHLIB) $(DESTINSTALLSITEARCH) \
		$(INST_BIN) $(DESTINSTALLSITEBIN) \
		$(INST_SCRIPT) $(DESTINSTALLSITESCRIPT) \
		$(INST_MAN1DIR) $(DESTINSTALLSITEMAN1DIR) \
		$(INST_MAN3DIR) $(DESTINSTALLSITEMAN3DIR)
	$(NOECHO) $(WARN_IF_OLD_PACKLIST) \
		$(PERL_ARCHLIB)/auto/$(FULLEXT)

pure_vendor_install :: all
	$(NOECHO) umask 022; $(MOD_INSTALL) \
		$(INST_LIB) $(DESTINSTALLVENDORLIB) \
		$(INST_ARCHLIB) $(DESTINSTALLVENDORARCH) \
		$(INST_BIN) $(DESTINSTALLVENDORBIN) \
		$(INST_SCRIPT) $(DESTINSTALLVENDORSCRIPT) \
		$(INST_MAN1DIR) $(DESTINSTALLVENDORMAN1DIR) \
		$(INST_MAN3DIR) $(DESTINSTALLVENDORMAN3DIR)

doc_perl_install :: all

doc_site_install :: all
	$(NOECHO) $(ECHO) Appending installation info to $(DESTINSTALLSITEARCH)/perllocal.pod
	-$(NOECHO) umask 02; $(MKPATH) $(DESTINSTALLSITEARCH)
	-$(NOECHO) umask 02; $(DOC_INSTALL) \
		"Module" "$(NAME)" \
		"installed into" "$(INSTALLSITELIB)" \
		LINKTYPE "$(LINKTYPE)" \
		VERSION "$(VERSION)" \
		EXE_FILES "$(EXE_FILES)" \
		>> $(DESTINSTALLSITEARCH)/perllocal.pod

doc_vendor_install :: all


uninstall :: uninstall_from_$(INSTALLDIRS)dirs
	$(NOECHO) $(NOOP)

uninstall_from_perldirs ::

uninstall_from_sitedirs ::
	$(NOECHO) $(UNINSTALL) $(SITEARCHEXP)/auto/$(FULLEXT)/.packlist

uninstall_from_vendordirs ::



# --- MakeMaker force section:
# Phony target to force checking subdirectories.
FORCE :
	$(NOECHO) $(NOOP)


# --- MakeMaker perldepend section:


# --- MakeMaker makefile section:
# We take a very conservative approach here, but it's worth it.
# We move Makefile to Makefile.old here to avoid gnu make looping.
$(FIRST_MAKEFILE) : Makefile.PL $(CONFIGDEP)
	$(NOECHO) $(ECHO) "Makefile out-of-date with respect to $?"
	$(NOECHO) $(ECHO) "Cleaning current config before rebuilding Makefile..."
	-$(NOECHO) $(RM_F) $(MAKEFILE_OLD)
	-$(NOECHO) $(MV)   $(FIRST_MAKEFILE) $(MAKEFILE_OLD)
	- $(MAKE) $(USEMAKEFILE) $(MAKEFILE_OLD) clean $(DEV_NULL)
	$(PERLRUN) Makefile.PL 
	$(NOECHO) $(ECHO) "==> Your Makefile has been rebuilt. <=="
	$(NOECHO) $(ECHO) "==> Please rerun the $(MAKE) command.  <=="
	$(FALSE)



# --- MakeMaker staticmake section:

# --- MakeMaker makeaperl section ---
MAP_TARGET    = perl
FULLPERL      = /usr/bin/perl

$(MAP_TARGET) :: static $(MAKE_APERL_FILE)
	$(MAKE) $(USEMAKEFILE) $(MAKE_APERL_FILE) $@

$(MAKE_APERL_FILE) : $(FIRST_MAKEFILE) pm_to_blib
	$(NOECHO) $(ECHO) Writing \"$(MAKE_APERL_FILE)\" for this $(MAP_TARGET)
	$(NOECHO) $(PERLRUNINST) \
		Makefile.PL DIR= \
		MAKEFILE=$(MAKE_APERL_FILE) LINKTYPE=static \
		MAKEAPERL=1 NORECURS=1 CCCDLFLAGS=


# --- MakeMaker test section:

TEST_VERBOSE=0
TEST_TYPE=test_$(LINKTYPE)
TEST_FILE = test.pl
TEST_FILES = t/*.t
TESTDB_SW = -d

testdb :: testdb_$(LINKTYPE)

test :: $(TEST_TYPE) subdirs-test

subdirs-test ::
	$(NOECHO) $(NOOP)


test_dynamic :: pure_all
	PERL_DL_NONLAZY=1 $(FULLPERLRUN) "-MExtUtils::Command::MM" "-e" "test_harness($(TEST_VERBOSE), '$(INST_LIB)', '$(INST_ARCHLIB)')" $(TEST_FILES)

testdb_dynamic :: pure_all
	PERL_DL_NONLAZY=1 $(FULLPERLRUN) $(TESTDB_SW) "-I$(INST_LIB)" "-I$(INST_ARCHLIB)" $(TEST_FILE)

test_ : test_dynamic

test_static :: test_dynamic
testdb_static :: testdb_dynamic


# --- MakeMaker ppd section:
# Creates a PPD (Perl Package Description) for a binary distribution.
ppd :
	$(NOECHO) $(ECHO) '<SOFTPKG NAME="$(DISTNAME)" VERSION="2.2.11">' > $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '    <ABSTRACT></ABSTRACT>' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '    <AUTHOR></AUTHOR>' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '    <IMPLEMENTATION>' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <REQUIRE NAME="AppConfig::" VERSION="1.52" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <ARCHITECTURE NAME="x86_64-linux-gnu-thread-multi-5.14" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '        <CODEBASE HREF="" />' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '    </IMPLEMENTATION>' >> $(DISTNAME).ppd
	$(NOECHO) $(ECHO) '</SOFTPKG>' >> $(DISTNAME).ppd


# --- MakeMaker pm_to_blib section:

pm_to_blib : $(FIRST_MAKEFILE) $(TO_INST_PM)
	$(NOECHO) $(ABSPERLRUN) -MExtUtils::Install -e 'pm_to_blib({@ARGV}, '\''$(INST_LIB)/auto'\'', q[$(PM_FILTER)], '\''$(PERM_DIR)'\'')' -- \
	  lib/Network/RCConfig.pm blib/lib/Network/RCConfig.pm \
	  lib/Boot/Label.pm blib/lib/Boot/Label.pm \
	  lib/Boot/Lilo.pm blib/lib/Boot/Lilo.pm \
	  lib/Boot/EFI.pm blib/lib/Boot/EFI.pm \
	  lib/Modules/Root.pm blib/lib/Modules/Root.pm \
	  lib/Modules/Generic.pm blib/lib/Modules/Generic.pm \
	  lib/Network/RawNetwork.pm blib/lib/Network/RawNetwork.pm \
	  lib/Network/SuSE8.pm blib/lib/Network/SuSE8.pm \
	  lib/SCConfig.pm blib/lib/SCConfig.pm \
	  lib/Modules/ModprobeConf.pm blib/lib/Modules/ModprobeConf.pm \
	  lib/Initrd/Generic.pm blib/lib/Initrd/Generic.pm \
	  lib/Boot/Grub.pm blib/lib/Boot/Grub.pm \
	  lib/Boot/Palo.pm blib/lib/Boot/Palo.pm \
	  lib/Util/Cmd.pm blib/lib/Util/Cmd.pm \
	  lib/Boot/Devfs.pm blib/lib/Boot/Devfs.pm \
	  lib/Time/Zone/RH.pm blib/lib/Time/Zone/RH.pm \
	  lib/Boot/Path.pm blib/lib/Boot/Path.pm \
	  lib/Hardware.pm blib/lib/Hardware.pm \
	  lib/Time/Zone/Generic.pm blib/lib/Time/Zone/Generic.pm \
	  lib/Modules/RcConfig.pm blib/lib/Modules/RcConfig.pm \
	  lib/Hardware/PCI/Table.pm blib/lib/Hardware/PCI/Table.pm \
	  lib/UserExit.pm blib/lib/UserExit.pm \
	  lib/Boot.pm blib/lib/Boot.pm \
	  lib/Initrd2.pm blib/lib/Initrd2.pm \
	  lib/Network/Interface.pm blib/lib/Network/Interface.pm \
	  lib/Modules/ModulesConf.pm blib/lib/Modules/ModulesConf.pm \
	  lib/Hardware/iSeries.pm blib/lib/Hardware/iSeries.pm \
	  lib/Boot/Iseries.pm blib/lib/Boot/Iseries.pm \
	  lib/Network/LinuxConf.pm blib/lib/Network/LinuxConf.pm \
	  lib/Initrd/Debian.pm blib/lib/Initrd/Debian.pm \
	  lib/Network/Generic.pm blib/lib/Network/Generic.pm \
	  lib/Time/HWSync.pm blib/lib/Time/HWSync.pm \
	  lib/Initrd/SuSE.pm blib/lib/Initrd/SuSE.pm \
	  lib/Modules/SuSE8.pm blib/lib/Modules/SuSE8.pm \
	  lib/Time/Zone/SuSE8.pm blib/lib/Time/Zone/SuSE8.pm \
	  lib/Util/FileMod.pm blib/lib/Util/FileMod.pm \
	  lib/Time/Rdate.pm blib/lib/Time/Rdate.pm \
	  lib/Initrd.pm blib/lib/Initrd.pm \
	  lib/Initrd/RH.pm blib/lib/Initrd/RH.pm \
	  lib/Boot/Aboot.pm blib/lib/Boot/Aboot.pm \
	  lib/Hardware/PCI/Detect.pm blib/lib/Hardware/PCI/Detect.pm \
	  lib/Time/Zone/Debian.pm blib/lib/Time/Zone/Debian.pm \
	  lib/Time.pm blib/lib/Time.pm \
	  lib/Keyboard.pm blib/lib/Keyboard.pm \
	  lib/Network.pm blib/lib/Network.pm \
	  lib/Modules/ConfModules.pm blib/lib/Modules/ConfModules.pm \
	  lib/Boot/Kboot.pm blib/lib/Boot/Kboot.pm \
	  lib/Time/NTP.pm blib/lib/Time/NTP.pm \
	  lib/Time/Zone.pm blib/lib/Time/Zone.pm \
	  lib/Boot/ZIPL.pm blib/lib/Boot/ZIPL.pm \
	  lib/Modules/ModutilsAliases.pm blib/lib/Modules/ModutilsAliases.pm \
	  lib/Boot/YaBoot.pm blib/lib/Boot/YaBoot.pm \
	  lib/Net/Netmask.pm blib/lib/Net/Netmask.pm \
	  lib/Network/Interfaces.pm blib/lib/Network/Interfaces.pm \
	  lib/Modules/Deps.pm blib/lib/Modules/Deps.pm 
	$(NOECHO) $(ABSPERLRUN) -MExtUtils::Install -e 'pm_to_blib({@ARGV}, '\''$(INST_LIB)/auto'\'', q[$(PM_FILTER)], '\''$(PERM_DIR)'\'')' -- \
	  lib/Util/Log.pm blib/lib/Util/Log.pm \
	  lib/Boot/Elilo.pm blib/lib/Boot/Elilo.pm \
	  lib/Modules/ModprobeD.pm blib/lib/Modules/ModprobeD.pm 
	$(NOECHO) $(TOUCH) pm_to_blib


# --- MakeMaker selfdocument section:


# --- MakeMaker postamble section:

POD2MAN_EXE := $(POD2MAN_EXE) "--center=System Configurator" "--release=v2.2.11"
POD2MAN5_EXE = $(POD2MAN_EXE) "--section=5"

deb_prep :: manifest
	perl -pi.bak -e 's/^VERSION.*/VERSION = 2.2.11/' debian/rules

deb :: deb_prep dist
	mkdir -p /tmp/scdeb
	mv systemconfigurator-2.2.11.tar.gz /tmp/scdeb && cd /tmp/scdeb && tar -xvzf systemconfigurator-2.2.11.tar.gz && cd systemconfigurator-2.2.11 && dpkg-buildpackage && rm -rf /tmp/scdeb/systemconfigurator-2.2.11
	echo "Debian Packages have been built in /tmp/scdeb"

rpm_prep ::
	cp -a ./sc.spec.in ./sc.spec && perl -pi -e 's/\@VERSION@/2.2.11/' ./sc.spec

rpm :: srpm 
	rpmbuild -tb $(NAME)-$(VERSION).tar.gz

srpm :: rpm_prep manifest dist
	rpmbuild -ts $(NAME)-$(VERSION).tar.gz

manext_install ::
	cd docs && \
	install -d $(DESTDIR)$(INSTALLMAN1DIR)/../man5 && \
	$(POD2MAN5_EXE) systemconfig.conf.pod $(DESTDIR)$(INSTALLMAN1DIR)/../man5/systemconfig.conf.5 && \
	cd ..

set_ver::
	perl -pi -e 's/EXEVERSION =.*/EXEVERSION = "2.2.11";/' ./blib/script/systemconfigurator
	perl -pi -e 's/EXEVERSION =.*/EXEVERSION = "2.2.11";/' ./bin/systemconfigurator
	cp -a ./sc.spec.in ./sc.spec && perl -pi -e 's/\@VERSION@/2.2.11/' ./sc.spec

all :: set_ver manifest

install :: manext_install



# End.
